apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  namespace: firstwebapp
spec:
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: abnerstelmastchuk/firstapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
